version: "3.9"

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"


services:
    auth:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        command: poetry run app
        volumes:
            - "./src/:/app/src"
        depends_on:
            - mongo
        logging: *logging

    mongo:
        image: mongo:7.0.12
        restart: always
        environment:
            MONGO_DB: "${MONGO_DB}"
            MONGO_USER: "${MONGO_USER}"
            MONGO_PASSWORD: "${MONGO_PASSWORD}"
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
        volumes:
            - auth_data:/data/db
        logging: *logging

    redis:
        image: redis:7.4-alpine
        restart: always
        command: redis-server --loglevel ${REDIS_LOG_LEVEL:-"warning"}
        volumes:
            - redis_data:/data
        logging: *logging

volumes:
    auth_data:
    redis_data:
