name: Docker Image CI for GHRC

on: [push]

jobs:
    tests:
        environment:
            name: tests

        strategy:
            max-parallel: 4
            matrix:
                python-version:
                    - "3.12.x"

        runs-on: ubuntu-latest
        env:
            ACTIONS_RUNNER_DEBUG: true
            ACTIONS_STEP_DEBUG: true
        steps:
            - name: Checkout code
              uses: actions/setup-python@v4
              with:
                submodules: true
                token: ${{ secrets.GH_SUBMODULE_TOKEN }}

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
                architecture: 'x64'

            - name: Install pipx and poetry
              run: |
                python -m pip install pipx
                python -m pipx ensurepath
                python -m pipx install poetry

            - name: Check for pyproject.toml
              run: |
               echo "Start listing files in the repository..."
               ls -la
               echo "End listing files in the repository..."

               if [ ! -f pyproject.toml ]; then
                  echo "pyproject.toml not found in $(pwd)"
                  exit 1
               fi

            - name: Install dependencies with poetry
              run: |
                poetry env use python
                poetry run pip install --upgrade pip setuptools
                poetry install --no-root

            - name: Run Tests
              run: |
                echo "Starting tests ..."
                poetry run pytest --cov --cov-report term --cov-report xml:coverage.xml tests

            - name: Upload coverage
              uses: actions/upload-artifact@v3
              with:
                name: coverage
                path: coverage.xml

    staging:
        needs: [tests]
        runs-on: ubuntu-latest
        env:
            ACTIONS_RUNNER_DEBUG: true
            ACTIONS_STEP_DEBUG: true
        environment:
            name: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  submodules: true
                  token: ${{ secrets.GH_SUBMODULE_TOKEN }}

            - name: Login to Docker registry
              run: |
                echo "Logging into Docker registry..."
                echo "${{ secrets.GHRC_PASSWORD }}" | docker login ghcr.io -u ${{ secrets.GHRC_USERNAME }} --password-stdin
                echo "Logging into Docker registry success"

            - name: Determine image tag and build Docker image
              id: build
              run: |
                if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/master" ]]; then
                  DOCKER_TAG="latest"
                elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
                  DOCKER_TAG="dev"
                elif [[ "${{ github.ref }}" =~ ^refs/heads/rc/([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
                  DOCKER_TAG="${{ github.ref }}_RC"
                else
                  exit 1
                fi

                echo "Building Docker image with tag $TAG..."
                docker build --no-cache -t ${{ secrets.GHRC_REGISTRY_ADDR }}:$DOCKER_TAG .
                docker push ${{ secrets.GHRC_REGISTRY_ADDR }}:$DOCKER_TAG
                echo "Build and push Docker image ok ..."
